version: '3.9'

services:
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - 8089:80
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/work/public
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    volumes:
      - .:/var/www/work
      - ./docker/app/conf/app.ini:/usr/local/etc/php/conf.d/app.ini
    depends_on:
      - db
  db:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:8.0
    container_name: db
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: carBunReserve
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-volume:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8087:80
    volumes:
      - /sessions
volumes:
  db-volume:
